name: Deploy Java App to Server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clone the repository
        uses: actions/checkout@v4
      - name: 🚀 Copy JAR file to Remote Server via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./"
          target: "/opt/java-app/"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 🛠 Restart systemd service on Remote Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/java-app/
            docker compose up -d --build
            
            
